services:
  service:
    container_name: hyunseoki_RADIO
    build:
      context: $PWD
      args:
        - USER
        - XDG_RUNTIME_DIR
    image: hyunseoki/radio
    tty: true
    stdin_open: true
    shm_size: 1TB
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]
              count: all
    volumes:
      - $PWD:/workspace
